### ISSUE TITLE
Error: Failed to fetch

### ISSUE THREAD

**Issue by AliYar-Khan** [imgly/background-removal-js#104]
It was working fine and suddenly it started giving this error message in the browser

```
err  ---> Error: Failed to fetch /models/medium with size 4194304 but got 0
    at resource.ts:57:1
    at async Promise.all (index 3)
    at async loadAsBlob (resource.ts:71:1)
    at async initInference (inference.ts:16:1)
    at async removeBackground (index.ts:32:1)
    
```

**Comment by DanielHauschildt** [comment]
This happens when the data can't be fetched. Have you tried clearing the cache?

**Comment by RenovJ** [comment]
same here

**Comment by mirko314** [comment]
The default CDN has changed from unpkg to `staticimgly.com`, which should resolve the original fetch failures. If you're still seeing this on v1.7.0, please reopen with details about your environment.
